In [2]:
import numpy as np

a= np.array([1,2,3,4])
b=np.array([2,3,4,5])
print(a*b)


[ 2  6 12 20]


In [3]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1.shape)
arr1.reshape(3,2)
# 3 row and 2 column

print(np.arange(1,10,2))
print(np.arange(1,10,2).shape)
print(np.arange(1,10,2).reshape(1,5))



(6,)
[1 3 5 7 9]
(5,)
[[1 3 5 7 9]]


In [4]:
np.ones((3,4))
np.eye(3,5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [5]:
# Vector Operation
ar1  = np.array([1,2,3,4,5,6])
ar2 = np.array([10,20,30,40,50,60])

print("Addition",ar1 + ar2)
print("Multiplication",ar1 * ar2)
print("Subtraction",ar1 - ar2)
print("Division",ar1 / ar2)

print(np.sqrt(ar1))
print(np.exp(ar1))

Addition [11 22 33 44 55 66]
Multiplication [ 10  40  90 160 250 360]
Subtraction [ -9 -18 -27 -36 -45 -54]
Division [0.1 0.1 0.1 0.1 0.1 0.1]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]


In [ ]:
# Statistical Concept

data  = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
mean = np.mean(data)
median = np.median(data)
varience = np.var(data)
std_dev = np.std(data)

print("Mean",mean)
print("Median",median)
print("Varience",varience)
print("Stan Deviation ",std_dev)


noramalized_data = (data-mean)/std_dev
# Normalized data means your mean is zero and standar deviation is one



Mean 7.5
Median 7.5
Varience 16.25
Stan Deviation  4.031128874149275


In [7]:
# Logical operation
data1 = np.array([1,2,3,4,5,6,7,8,9])

print(data1>5)
print(data1[data1>5])
print(data1[(data1 > 3) & (data1 < 8)])  # Output: [4 5 6 7]
print(data1)



[False False False False False  True  True  True  True]
[6 7 8 9]
[4 5 6 7]
[1 2 3 4 5 6 7 8 9]
